version = 0.1
[count-app.deploy.parameters]
stack_name = "count-app-stack"
s3_bucket = "count-lambda-s3-bucket"
s3_prefix = "count-app-stack"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
fail_on_empty_changeset = false