AWSTemplateFormatVersion: "2010-09-09"
Description: "GitHub Role"

# Parameters:
#   AppName:
#     Description: Your App Name
#     Type: String
#     Default: serverless-app

Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
  OIDCRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud:
                  - "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - "repo:kimsarai/serverless-application:*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      RoleName: "aws-identity-providers-github-actions"
      Tags:
        - Key: "Name"
          Value: "aws-identity-providers-github-actions"
Outputs:
  Role:
    Value: !GetAtt OIDCRole.Arn