AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: apigw + lambda + dynamodb

Globals:
  Function:
    Runtime: python3.9

Parameters: 
  AppName:
    Description: Your App Name
    Type: String

Resources:
  CountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-count-function
      Description: Count-Function
      CodeUri: ../app/functions
      Handler: count.lambda_handler 
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref CountTable
      Events:
        AppMethod:
          Type: Api
          Properties:
            RestApiId: !Ref CountAPI
            Path: /count
            Method: GET
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref CountTable
      Tags:
        Name: !Sub ${AppName}-count-function

  CountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: count-app-table
      PrimaryKey:
        Name: name
        Type: String
  CountAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AppName}-count-api
      Description: Sample-API
      StageName: stg
      EndpointConfiguration:
        Type: REGIONAL
      Tags:
        Name: !Sub ${AppName}-count-api

Outputs:
  ApiEndpoint:
    Description: "API Gateway Endpoint URL"
    Value: !Sub "https://${CountAPI}.execute-api.${AWS::Region}.amazonaws.com/Stage/count"