name: Deploy-AWS-CloudFormation
 
on:
  push:
    branches:
      - develop
  workflow_dispatch:
 
env: 
  TEMPLATE_FILE: CFn/template.yml
  CONFIG_ENV: count-app

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit-test
        id: unit-test
        continue-on-error: true
        run: |
          pip install -r requirements.txt -q
          export REPOSITORY_HOME=$(pwd)
          cd tests/
          pytest -v --cov --cov-branch --cov-report=html test_count.py
          cd ${REPOSITORY_HOME}

      - name: Setup python
        if: steps.unit-test.outcome == 'success'
        uses: actions/setup-python@v3

      - name: Setup aws-sam
        if: steps.unit-test.outcome == 'success'
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        if: steps.unit-test.outcome == 'success'
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-github-actions
          role-session-name: github_actions_OIDC_role
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
      - name: Build & Deploy Cloudformation stacks
        if: steps.unit-test.outcome == 'success'
        run: |
          sam build --use-container --config-env ${CONFIG_ENV} --template-file ${TEMPLATE_FILE} --parameter-overrides AppName=serverless-app 
          sam deploy --config-env ${CONFIG_ENV} --template-file ${TEMPLATE_FILE} --parameter-overrides AppName=serverless-app 
